# 監視銘柄リスト
tickers:
  - AAPL
  - AMAT
  - AMD
  - AMZN
  - APP
  - ASTS
  - AUR
  - BBAI
  - CAKE
  - CEG
  - CELH
  - COHR
  - CRM
  - CRWV
  - ELF
  - GOOGL
  - GTLB
  - IONQ
  - IOT
  - JOBY
  - KO
  - LITE
  - LLY
  - LMT
  - META
  - MRVL
  - MSFT
  - NOW
  - NVDA
  - ONDS
  - PLTR
  - QBTS
  - RBRK
  - RCAT
  - RKLB
  - RLMD
  - RXRX
  - S
  - SOFI
  - SOUN
  - TSLA
  - UNH
  - VRT
  - VWAV
