# 監視銘柄リスト
tickers:
  - AAPL
  - AMD
  - AMZN
  - APP
  - AUR
  - BBAI
  - CAKE
  - CELH
  - CRWV
  - FIG
  - GOOGL
  - KO
  - META
  - MSFT
  - NOW
  - NVDA
  - ONDS
  - PLTR
  - RCAT
  - RDW
  - RKLB
  - SOFI
  - SOUN
  - TSLA
  - UNH
  - VWAV
  - XNDU
