# 監視銘柄リスト
tickers:
  - AAPL
  - AMD
  - AMZN
  - APP
  - APPL
  - BBAI
  - CAKE
  - CELH
  - CRWV
  - FIG
  - GOOGL
  - KO
  - META
  - MSFT
  - NVDA
  - ONDS
  - PLTR
  - RKLB
  - SOFI
  - SOUN
  - TSLA
  - UNH
